version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    networks:
      - selenoid

  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=10.0.47.57:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - selenoid


  tests:
    container_name: pytests
    image: pytests:latest
    build:
      dockerfile: tests/Dockerfile
    command: ./wait-for-it.sh opencart 8080 pytest --browser=chrome  --url=http://10.0.47.57:8081/ tests/OPENCART_REG_USER/
    depends_on:
      - opencart
    networks:
      - selenoid

networks:
  selenoid:
    driver: bridge
    external: true

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
